# variables:
  # SERVICE_NAME: go-api # for example: product-api-pangpang-brand from  https://gitlab.p2shop.cn:8443/data/rtc-data/blob/qa/config.qa.yml
  # FOLDERNAME: ""  # for example: nomni/
  # GITLABWITCH: "p2shop" # p2shop srx srx-p2shop
    # for example:
    # p2shop: 1. git on gitlab.p2shop.cn, 2. jenkins on ci.p2shop.com.cn
    # srx: 1. git on gitlab.srxcloud.com, 2. jenkins on jenkins.srxcloud.com
    # srx-p2shop: 1. git on gitlab.srxcloud.com, 2. jenkins on ci.p2shop.com.cn
variables:
  SERVICE_NAME: go-api
include: 
  - '******'
