# variables:
  # SERVICE_NAME: go-api # Please confirm: 1. The base database has been added (database:pangpang-mysql), 2. The project startup information has been added (database:rtc)
  # FOLDERNAME: ""  # for example: nomni/
  # GOBUILD_ENV: ""
  # GOTEST_ENV: "-e JWT_SECRET=1234"
  # RTC_ENV: " --docker-no-login --env production "
variables:
  SERVICE_NAME: go-api
include: 
  - project: 'open/gitlab-ci'
    file: '/templates/go.gitlab-ci.yml'