database:
  driver: mysql
  connection: xxx:xxx@tcp(10.173.208.142:3307)/fruit?charset=utf8&parseTime=True&loc=UTC
  name: fruit
  logger:
    kafka:
      brokers:
        - 10.173.208.142:9092
      topic: sqllog
eventBroker:
  kafka:
    brokers:
      - 10.173.208.142:9092
    topic: fruit
behaviorLog:
  kafka:
    brokers:
      - 10.173.208.142:9092
    topic: behaviorlog
serviceName: go-api
httpport: 8080