database:
  driver: mysql
  connection: fruit:Eland123@tcp(192.168.0.52:3306)/fruit?charset=utf8&parseTime=True&loc=UTC
  logger:
    kafka:
      brokers:
        - 192.168.0.76:9092
        - 192.168.0.145:9092
        - 192.168.0.148:9092
      topic: sqllog
behaviorLog:
  kafka:
    brokers:
      - 192.168.0.76:9092
      - 192.168.0.145:9092
      - 192.168.0.148:9092
    topic: behaviorlog
serviceName: go-api
httpport: 8080