database:
  driver: mysql
  connection: fruit:Eland123@tcp(rm-uf697cmu717ius9i3.mysql.rds.aliyuncs.com:3306)/fruit?charset=utf8&parseTime=True&loc=UTC
  logger:
    kafka:
      brokers:
        - 10.26.205.20:9092
        - 10.27.116.104:9092
        - 10.27.121.103:9092
      topic: sqllog
behaviorLog:
  kafka:
    brokers:
      - 10.26.205.20:9092
      - 10.27.116.104:9092
      - 10.27.121.103:9092
    topic: behaviorlog
serviceName: go-api
httpport: 8080