database:
  driver: mysql
  connection: root:1234@tcp(127.0.0.1:3308)/fruit?charset=utf8&parseTime=True&loc=UTC&multiStatements=true
  logger:
    kafka:
      brokers:
        - 127.0.0.1:9092
      topic: sqllog
behaviorLog:
  kafka:
    brokers:
      - 127.0.0.1:9092
    topic: behaviorlog
serviceName: go-api
httpport: 8080