database:
  driver: mysql
  connection: fruit:Eland123@tcp(10.30.8.55:3306)/fruit?charset=utf8&parseTime=True&loc=Local
  name: fruit
  logger:
    kafka:
      brokers:
        - 10.30.8.55:9092
      topic: sqllog
behaviorLog:
  kafka:
    brokers:
      - 10.30.8.55:9092
    topic: behaviorlog
serviceName: go-api
httpport: 8080