envs:
  - APP_ENV=test
  - SQL_DRIVER=mssql
  - FRUIT_CONN=driver={sql server};server=test-sqlserver;user id=sa;password=Eland123;database=fruit;port=1433;
isProjectKafka: false
ports: 
  - 8080
databases:
  sqlserver:
    - fruit
streamNames:
execPath: 