envs:
  - APP_ENV=test
  - FRUIT_CONN=root:1234@tcp(test-mysql:3306)/fruit?charset=utf8&parseTime=True&loc=UTC
isProjectKafka: false
ports: 
  - 8080
databases:
  - mysql
  - sqlserver
streamNames:
execPath: 